### ISSUE TITLE
Error when writing thumbs with ConvertImages.php

### ISSUE THREAD

**Issue by cooperdk** [octfx/mediawiki-extension-WebP#10]
php extensions/WebP/maintenance/ConvertImages.php --titles File1.jpg,File2.jpg

[4dd3705fe3a5bfb428854666] [no req]   TypeError: explode() expects parameter 2 to be string, int given
Backtrace:
from /home/spademanns/public_html/extensions/WebP/maintenance/ConvertImages.php(35)
#0 /home/spademanns/public_html/extensions/WebP/maintenance/ConvertImages.php(35): explode()
#1 /home/spademanns/public_html/maintenance/doMaintenance.php(114): ConvertImages->execute()
#2 /home/spademanns/public_html/extensions/WebP/maintenance/ConvertImages.php(136): require_once(string)
#3 {main}

**Comment by cooperdk** [comment]
Never mind, this was because it required a = between titles and the filelist. The help didn't make that clear.
I feel like the maintenance script should maybe be a python script instead, if possible, since apparently a lot happens in the php script that also makes it skip **A LOT** of files without being clear about anything.

Better verbosity is desired. There is NO output (and the debug output is just an unusable globals export).
